### PR TITLE
Adds test data for Paragraph.

### PR DESCRIPTION
**Pull request by llmunguia**
Adds a select set of MLPerf(TM)'s benchmarks to use as input for Paragraph.

### CODE REVIEW

**Comment by nicmcd** [comment]
@michael-isaev, should be push this to paragraph-sim/paragraph-core instead?

**Comment by michael-isaev** [comment]
I think we should post it here first, and then fork to `paragraph-sim/hlo-examples` in some folder like "mlperf_training_v0.7" and disclose that we forked from this repo.

**Review by michael-isaev — CHANGES_REQUESTED** [review]
@llmunguia Could you please change stats filenames to correspond to hlo filenames, i.e. `paragraph/data/bert-hlo-stats.csv` -> `paragraph/data/bert-4x8-TPUv3-after-stats.csv` to make stats use less ambiguous?

**Review by michael-isaev — CHANGES_REQUESTED** [review]
@llmunguia the stats files say in comment that benchmarks were running on TPUv4, while HLO filenames imply TPUv3. Could you please make the description consistent?

**Review by michael-isaev — APPROVED** [review]

**Pull request merged**
